[package]
name = "network_bot_rust"
version = "0.1.0"
authors = ["Igarashi Syo <igara1119@gmail.com>"]

[dependencies]
regex = "1.0.2"
reqwest = "0.8.7"
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.24"
